name: Documentation Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Use PHP 8.0
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
      
      - name: Install Dependencies
        run: |
          composer install
      
      - name: Generate Documentation
        run: |
          vendor/bin/daux generate --source=src/ --destination=doc --delete
      
      - name: Rsync to Distant Environment
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -uvr --delete --exclude-from="./CI/exclude-file.txt"
          remote_path: /kunden/homepages/3/d383283311/htdocs/Subdomains/wonderwpdoc
          remote_host: ${{ secrets.DEPLOY_HOSTNAME }}
          remote_user: ${{ secrets.DEPLOY_USERNAME }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          path: /doc/*

      #- name: Slack Notification
      #  uses: rtCamp/action-slack-notify@v2
      #  env:
      #    SLACK_CHANNEL: jenkins
      #    SLACK_COLOR: ${{ job.status }}
      #    #SLACK_ICON : https://avatars.slack-edge.com/2017-08-16/226685234736_8284433bd58b492ed49b_512.jpg
      #    SLACK_MESSAGE: "Documentation build status : ${{ job.status }}"
      #    SLACK_USERNAME: Won
      #    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
